import {RootState} from '@services/store';
import {createSelector} from 'reselect';

export const selectHomeData = createSelector(
  [
    (state: RootState) => state.post.posts,
    (state: RootState) => state.post.loading,
    (state: RootState) => state.post.page,
    (state: RootState) => state.post.hasNextPage,
    (state: RootState) => state.stories.storyDetails,
    (state: RootState) => state.stories.followingUsers,
    (state: RootState) => state.stories.myStories,
    (state: RootState) => state.user.user,
    (state: RootState) => state.stories.lastRefresh,
  ],
  (
    posts,
    loading,
    page,
    hasNextPage,
    storyDetails,
    followingUsers,
    myStories,
    user,
    lastRefresh,
  ) => ({
    posts,
    loading,
    page,
    hasNextPage,
    storyDetails,
    followingUsers,
    myStories,
    user,
    lastRefresh,
  }),
);

export const selectItemHomeData = createSelector(
  [
    (state: RootState) => state.reactions.likePosts,
    (state: RootState) => state.user.refreshToken,
    (state: RootState) => state.user.user?._id,
    (state: RootState) => state.user.user?.handleName,
    (state: RootState) => state.user.user?.username, 
    (state: RootState) => state.relation.followers,
    (state: RootState) => state.relation.following,
    (state: RootState) => state.relation.loading,
    (state: RootState) => state.bookmark.itemsByPlaylist,
    (state: RootState) => state.bookmark.playlists,
  ],
  (
    likePosts,
    refreshToken,
    userID,
    handleName,
    username,
    followers,
    following,
    loading,
    itemsByPlaylist,
    playlists,
  ) => ({
    likePosts,
    refreshToken,
    userID,
    handleName,
    username,
    followers,
    following,
    loading,
    itemsByPlaylist,
    playlists,
  }),
);
